name: demo-Tagless-Final-db
version: 0.1.0.0
github: mingyuchoo/demo-Tagless-Final-db
license: BSD-3-Clause
author: Mingyu Choo
maintainer: mingyuchoo@gmail.com
copyright: Mingyu Choo 2025
synopsis: Short description of your package
category: Web
description: Please see the README on GitHub at <https://github.com/mingyuchoo/demo-Tagless-Final-db#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.18 && < 5
  - containers
  - flow
  - parallel

default-extensions:
  - DataKinds
  - ExplicitForAll
  - StandaloneKindSignatures
  - TypeApplications

ghc-options:
  - -Wall
  - -O2
  - -haddock

language: GHC2021

library:
  source-dirs: src

executables:
  demo-Tagless-Final-db-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - demo-Tagless-Final-db

tests:
  demo-Tagless-Final-db-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - demo-Tagless-Final-db
      - hspec
      - doctest
      - doctest-discover
