name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: latest
      - name: Cache Stack
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'package.yaml', 'todo-list.cabal') }}
      - name: Build
        run: stack build --test --no-run-tests
      - name: Test
        run: stack test
