services:
  redis:
    image: redis:7-alpine
    container_name: scotty-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT_NAME: scotty-t02-clean-archi
    container_name: scotty-t02-clean-archi-app
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
  redis_data:
    driver: local