# https://www.stackage.org/lts-24.20
resolver: lts-24.20

packages:
- .

extra-package-dbs: []
extra-deps: []
flags: {}

docker:
  enable: true
  image: "fpco/stack-build:lts"
  container-name: "stdin"
  auto-pull: true
  persist: false
  set-user: true
  stack-exe: host
  run-args: []
  env:
    - "LC_ALL=C.UTF-8"

#nix:
#  enable: true
#  pure: true
#  packages:
#  - zlib
#  - glpk
#  - pcre
#  #shell-file: shell.nix
#  nix-shell-options: []
#  path: []
#  add-gc-roots: false
