name: words
version: 0.1.0.0
github: mingyuchoo/words
license: BSD-3-Clause
author: Mingyu Choo
maintainer: mingyuchoo@gmail.com
copyright: 2025, Mingyu Choo
synopsis: Short description of your package
category: CLI
description: Please see the README on GitHub at <https://github.com/mingyuchoo/words#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
- base
- containers
- flow
- parallel
- random

default-extensions:
  - DataKinds
  - ExplicitForAll
  - GADTs
  - KindSignatures
  - StandaloneKindSignatures
  - TypeApplications

ghc-options:
  - -Wall
  - -O2
  - -haddock

language: GHC2024

library:
  source-dirs: src

executables:
  words-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - words

tests:
  words-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - words
      - hspec
      - doctest
      - doctest-discover
