name:                ThreepennyAddress
version:             0.1.0.0
github:              mingyuchoo/ThreepennyAddress
license:             BSD-3-Clause
author:              Mingyu Choo
maintainer:          mingyuchoo@gmail.com
copyright:           2026 Mingyu Choo
synopsis:            Short description of your package
category:            Web
description:         Please see the README on GitHub at <https://github.com/mingyuchoo/ThreepennyAddress#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.18 && < 5
- containers
- directory
- flow
- mtl
- parallel
- text
- threepenny-gui
- aeson
- QuickCheck
- regex-tdfa
- hspec
- stm

default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- ExplicitForAll
- GADTs
- KindSignatures
- StandaloneKindSignatures
- OverloadedStrings
- TypeApplications

ghc-options:
- -Wall
- -O2
- -haddock

language: GHC2021

library:
  source-dirs: src

executables:
  ThreepennyAddress-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ThreepennyAddress

tests:
  ThreepennyAddress-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ThreepennyAddress
    - hspec
    - doctest
    - doctest-discover
