services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME:-azure-openai-haskell-agent}
    container_name: ${PROJECT_NAME:-azure-openai-haskell-agent}-app
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    restart: unless-stopped
    env_file:
      - ../backend/.env
    environment:
      - PORT=8000
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT:-gpt-5-chat}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-04-01-preview}
