name:                bfs-escape-maze
version:             0.1.0.0
github:              "mingyuchoo/bfs-escape-maze"
license:             BSD-3-Clause
author:              "Mingyu Choo"
maintainer:          "mingyuchoo@gmail.com"
copyright:           "2023 Mingyu Choo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mingyuchoo/bfs-escape-maze#readme>

dependencies:
- base
- array
- containers
- flow
- lens
- parallel
- text

default-extensions:
- StandaloneKindSignatures

ghc-options:
- -Wall
- -O2
- -haddock

library:
  source-dirs: src

executables:
  bfs-escape-maze-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - bfs-escape-maze

tests:
  bfs-escape-maze-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - bfs-escape-maze
    - hspec
    - hspec-discover
