name:                persist-postgresql-init
version:             0.1.0.0
github:              "mingyuchoo/persist-postgresql-init"
license:             BSD-3-Clause
author:              "Mingyu Choo"
maintainer:          "mingyuchoo@gmail.com"
copyright:           "Mingyu Choo"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Short description of your package
category:            Web
description:         Please see the README on GitHub at <https://github.com/mingyuchoo/persist-postgresql-init#readme>

dependencies:
- base
- aeson
- bytestring
- esqueleto
- hedis
- monad-logger
- mtl
- persistent
- persistent-postgresql
- persistent-template
- servant
- servant-client
- servant-server
- text
- time
- transformers
- warp

default-extensions:
- DataKinds
- DerivingStrategies
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- StandaloneDeriving
- TemplateHaskell
- TypeFamilies
- TypeOperators
- UndecidableInstances

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  migrate-db:
    main:                MigrateDB.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - persist-postgresql-init
  run-server:
    main:                RunServer.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - persist-postgresql-init

tests:
  api-tests:
    main:                APITests.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - persist-postgresql-init
    - hspec
    - http-client
    - http-client-tls
