name: parallel-using-par
version: 0.1.0.0
github: "mingyuchoo/parallel-using-par"
license: BSD-3-Clause
author: "Mingyu Choo"
maintainer: "mingyuchoo@gmail.com"
copyright: "2023 Mingyu Choo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mingyuchoo/parallel-using-par#readme>

dependencies:
- base
- containers
- flow
- parallel # IMPORTANT

default-extensions:
- StandaloneKindSignatures

ghc-options:
- -Wall
- -O2
- -haddock

library:
  source-dirs: src

executables:
  parallel-using-par-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4 # USING 4 CORES
    dependencies:
    - parallel-using-par

tests:
  parallel-using-par-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -dyamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4 # USING 4 CORES
    dependencies:
    - parallel-using-par
    - doctest
    - doctest-discover
    - hspec