version: '3'

services:
  postgres:
    image: postgres:17.6
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:8.2.0
    container_name: redis
    ports:
      - "6379:6379"

