name: dynamic-typing
version: 0.1.0.0
github: mingyuchoo/dynamic-typing
license: BSD-3-Clause
author: Mingyu Choo
maintainer: mingyuhcoo@gmail.com
copyright: 2025, Mingyu Choo
synopsis: Short description of your package
category: CLI
description: Please see the README on GitHub at <https://github.com/mingyuchoo/dynamic-typing#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
- base
- containers
- flow
- parallel

default-extensions:
  - StandaloneKindSignatures
  - TypeApplications

ghc-options:
  - -Wall
  - -O2
  - -haddock

language: Haskell2010

library:
  source-dirs: src

executables:
  dynamic-typing-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - dynamic-typing

tests:
  dynamic-typing-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - dynamic-typing
      - hspec
      - doctest
      - doctest-discover
