name: backend
version: 0.1.0.0
github: "mingyuchoo/backend"
license: BSD-3-Clause
author: "Mingyu Choo"
maintainer: "mingyuchoo@gmail.com"
copyright: "2025 Mingyu Choo"

extra-source-files:
- README.md

data-files:
- static/**/*

description: Azure OpenAI client in Haskell

dependencies:
- base
- text
- aeson
- bytestring
- http-client
- http-client-tls
- http-types
- dotenv
- wai
- warp
- servant
- servant-server
- servant-swagger
- servant-swagger-ui
- swagger2
- mtl
- transformers
- uuid
- time
- lens
- flow

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Lib
  - Domain.Entities
  - Domain.Ports
  - Application.UseCases
  - Infrastructure.AzureOpenAI
  - Presentation.API
  - Presentation.Server

executables:
  backend-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
