#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
target="$repo_root/docs/generated/api-index.md"
temporary="$(mktemp)"
trap 'rm -f "$temporary"' EXIT

# 원본은 docs/contracts/api 아래의 계약 문서 머리말입니다.
# 머리말 형식은 docs/contracts/api/README.md가 규정합니다.
python3 - "$repo_root" "$temporary" <<'PY'
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
out = Path(sys.argv[2])
directory = root / "docs/contracts/api"

SKIP = {"README.md", "CONTRACT-TEMPLATE.md"}


def field(text: str, name: str) -> str:
    match = re.search(rf"^-\s*{name}:\s*(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else "미기재"


rows = []
for document in sorted(directory.glob("*.md")):
    if document.name in SKIP:
        continue
    text = document.read_text(encoding="utf-8")
    title = re.search(r"^#\s*API Contract:\s*(.+)$", text, re.MULTILINE)
    rows.append(
        (
            title.group(1).strip() if title else document.stem,
            document.name,
            field(text, "소유 패키지"),
            field(text, "버전"),
            field(text, "상태"),
            field(text, "소비자"),
        )
    )

if rows:
    table = "\n".join(
        f"| [{title}](../contracts/api/{name}) | {owner} | {version} | {status} | {consumers} |"
        for title, name, owner, version, status, consumers in rows
    )
    body = (
        "| 계약 | 소유 패키지 | 버전 | 상태 | 소비자 |\n"
        "|---|---|---|---|---|\n"
        f"{table}\n"
    )
else:
    body = "현재 등록된 API 계약이 없습니다.\n"

out.write_text(
    "# API Index\n"
    "\n"
    "<!-- AUTOGENERATED: scripts/context/generate-api-index.sh -->\n"
    "\n"
    "원본: `docs/contracts/api`의 계약 문서 머리말\n"
    "\n"
    f"{body}"
    "\n"
    "라우트 수준의 사실은 `docs/generated/route-map.md`에 있습니다.\n"
    "이 파일을 직접 수정하지 마십시오.\n",
    encoding="utf-8",
)
PY

if [[ "${1:-}" == "--check" ]]; then
  if ! cmp -s "$temporary" "$target"; then
    printf '생성 문서가 오래되었습니다: %s\n' "$target" >&2
    exit 1
  fi
  printf 'API 인덱스 최신 상태 확인\n'
else
  cp "$temporary" "$target"
  printf '생성 완료: %s\n' "$target"
fi
