---
name: integ-hspec01
version: 0.1.0.0
github: "mingyuchoo/integ-hspec01"
license: BSD-3-Clause
author: "Mingyu Choo"
maintainer: "mingyuchoo@gmail.com"
copyright: "2023 Mingyu Choo"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mingyuchoo/integ-hspec01#readme>

dependencies:
  - base
  - containers
  - flow
  - parallel

default-extensions:
  - StandaloneKindSignatures

ghc-options:
  - -Wall
  - -O2
  - -haddock

library:
  source-dirs: src

executables:
  integ-hspec01-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - integ-hspec01

tests:
  integ-hspec01-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - integ-hspec01
      - hspec
      - QuickCheck
