name: pizza-store
version: 0.1.0.0
github: "mingyuchoo/pizza-store"
license: BSD3
author: "mingyuchoo"
maintainer: "mingyuchoo"
copyright: "2023 Mingyu Choo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mingyuchoo/pizza-store#readme>

dependencies:
- base >= 4.9.1.0 && < 5
- containers
- flow
- parallel

default-extensions: []
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pizza-store-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - pizza-store

tests:
  pizza-store-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - pizza-store
    - doctest
    - doctest-discover
    - hspec