# https://www.stackage.org/lts-24.4
resolver: lts-24.4

packages:
- .

extra-package-dbs: []
extra-deps: []
flags: {}

#nix:
#  enable: true
#  pure: true
#  packages:
#  - zlib
#  - glpk
#  - pcre
#  #shell-file: shell.nix
#  nix-shell-options: []
#  path: []
#  add-gc-roots: false
