name: transactions
version: 0.1.0.0
github: mingyuchoo/transactions
license: BSD-3-Clause
author: Mingyu Choo
maintainer: mingyuhcoo@gmail.com
copyright: 2025, Mingyu Choo
synopsis: Short description of your package
category: CLI
description: Please see the README on GitHub at <https://github.com/mingyuchoo/transactions#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
- base
- containers
- mwc-random
- stm


default-extensions:
  - StandaloneKindSignatures
  - TypeApplications

ghc-options:
  - -Wall
  - -O2
  - -haddock

language: Haskell2010

library:
  source-dirs: src

executables:
  transactions-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - transactions

tests:
  transactions-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - transactions
      - hspec
      - doctest
      - doctest-discover
