name: web-crawler
version: 0.1.0.0
github: mingyuchoo/web-crawler
license: BSD-3-Clause
author: Mingyu Choo
maintainer: mingyuchoo@gmail.com
copyright: 2025, Mingyu Choo
synopsis: Short description of your package
category: CLI
description: Please see the README on GitHub at <https://github.com/mingyuchoo/web-crawler#readme>
extra-source-files:
  - README.md
  - CHANGELOG.md
dependencies:
  - base
  - bytestring
  - containers
  - flow
  - parallel
  - http-conduit
  - tagsoup
  - text
default-extensions:
  - StandaloneKindSignatures
  - TypeApplications
ghc-options:
  - -Wall
  - -O2
  - -haddock
language: Haskell2010
library:
  source-dirs: src
executables:
  web-crawler-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - web-crawler
tests:
  web-crawler-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - web-crawler
      - hspec
      - doctest
      - doctest-discover
