resolver: lts-24.20

packages:
- .

docker:
  enable: true
  image: fpco/stack-build:lts-24.20
  auto-pull: true
  persist: false
  container-name: "vanilla-rnn-init"
  run-args: []
  stack-exe: host
  set-user: true

#nix:
#  enable: true
#  pure: true
#  packages:
#    - zlib
#    - glpk
#    - pcre
#  #shell-file: shell.nix
#  nix-shell-options: []
#  path: []
#  add-gc-roots: false
