name: geometry
version: 0.1.0.0
github: mingyuchoo/geometry
license: BSD-3-Clause
author: Mingyu Choo
maintainer: mingyuchoo@gmail.com
copyright: Mingyu Choo 2024
synopsis: Short description of your package
category: CLI
description: Please see the README on GitHub at <https://github.com/mingyuchoo/geometry#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
- base
- containers
- flow
- parallel

default-extensions:
  - DataKinds
  - ExplicitForAll
  - GADTs
  - KindSignatures
  - StandaloneKindSignatures
  - TypeApplications

ghc-options:
  - -Wall
  - -O2
  - -haddock

language: GHC2024

library:
  source-dirs: src

executables:
  geometry-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - geometry

tests:
  geometry-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - geometry
      - hspec
      - doctest
      - doctest-discover
