# https://www.stackage.org/lts-24.4
resolver: lts-24.4

packages:
- .

extra-package-dbs: []
extra-deps:
- hpack-0.38.1
flags: {}

docker:
  enable: true
  image: "fpco/stack-build:lts-24.4"
  container-name: "sample-name"
  auto-pull: true
  persist: true
  set-user: true
  stack-exe: host
  run-args: []
  env:
    - "LC_ALL=C.UTF-8"

#nix:
#  enable: true
#  pure: true
#  packages:
#  - zlib
#  - glpk
#  - pcre
#  #shell-file: shell.nix
#  nix-shell-options: []
#  path: []
#  add-gc-roots: false
