name:                tto
version:             0.1.0.0
github:              mingyuchoo/tto
license:             BSD-3-Clause
author:              Mingyu Choo
maintainer:          mingyuchoo@gmail.com
copyright:           Mingyu Choo 2025
synopsis:            Short description of your package
category:            Web
description:         Please see the README on GitHub at <https://github.com/mingyuchoo/tto#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.18 && < 5
- brick
- containers
- flow
- microlens
- microlens-th
- mtl
- parallel
- text
- time
- vector
- vty
- sqlite-simple
- transformers
- aeson
- yaml
- bytestring
- directory
- filepath

default-extensions:
- DataKinds
- DeriveGeneric
- ExplicitForAll
- GADTs
- KindSignatures
- StandaloneKindSignatures
- OverloadedStrings
- TemplateHaskell
- TypeApplications

ghc-options:
- -Wall
- -O2
- -haddock

language: GHC2021

library:
  source-dirs: src

executables:
  tto:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-inconsistent-flags
    dependencies:
    - tto

tests:
  tto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-inconsistent-flags
    dependencies:
    - tto
    - hspec
    - doctest
    - doctest-discover
    - microlens
    - brick
    - vector
