name:                no-zero-world
version:             0.1.0.0
github:              mingyuchoo/no-zero-world
license:             BSD 3-Clause
author:              Mingyu Choo
maintainer:          mingyuchoo@gmail.com
copyright:           Mingyu Choo 2024
synopsis:            Short description of your package
category:            CLI
description:         Please see the README on GitHub at <https://github.com/mingyuchoo/no-zero-world#readme>

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base
- containers
- flow
- parallel

default-extensions:
- StandaloneKindSignatures

ghc-options:
- -Wall
- -O2
- -haddock

language: Haskell2010

library:
  source-dirs: src

executables:
  no-zero-world-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - no-zero-world

tests:
  no-zero-world-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - no-zero-world
    - hspec
    - doctest
    - doctest-discover
