name: warp-t03-clean-archi
version: 0.1.0.0
github: mingyuchoo/warp-t03-clean-archi
license: BSD-3-Clause
author: Mingyu Choo
maintainer: mingyuhcoo@gmail.com
copyright: 2025, Mingyu Choo
synopsis: Short description of your package
category: CLI
description: Please see the README on GitHub at <https://github.com/mingyuchoo/warp-t03-clean-archi#readme>

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - aeson
  - base
  - bytestring
  - flow
  - http-types
  - wai
  - warp
  - text
  - sqlite-simple
  - uuid
  - time

default-extensions:
  - StandaloneKindSignatures
  - TypeApplications
  - ScopedTypeVariables
ghc-options:
  - -Wall
  - -O2
  - -haddock
language: GHC2024

library:
  source-dirs: src
  exposed-modules:
    - Lib

executables:
  warp-t03-clean-archi-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - warp-t03-clean-archi

tests:
  warp-t03-clean-archi-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -dynamic
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
    dependencies:
      - warp-t03-clean-archi
      - hspec
      - doctest
      - doctest-discover
