services:
  db:
    image: postgres:16-alpine
    container_name: postgresql-simple-init-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT_NAME: postgresql-simple-init
    image: postgresql-simple-init:latest
    container_name: postgresql-simple-init-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8000:8000"
    volumes:
      - ../static:/app/static:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/app/app-exe"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pgdata:
    driver: local
